name: Sync to Stats Repo

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Secondary Repository
        env:
          SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          git config --global user.name "GitHub Action Sync"
          git config --global user.email "action@github.com"
          git rm -rf --cached .github
          git commit -m "Exclude workflows from sync" || true
          git remote add destination "https://x-access-token:${SYNC_TOKEN}@github.com/wyliemckinty/NCU-Cricket-Stats.git"
          git push destination main:main --force
